name:                wstat
version:             0.1.0.0
github:              "parof/wstat"
license:             BSD3
author:              "Francesco Parolini, Denis Mazzucato"
maintainer:          "example@example.com"
copyright:           "2018 Francesco Parolini, Denis Mazzucato"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wstat#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers

library:
  source-dirs: src

executables:
  wstat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wstat

tests:
  wstat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wstat
    - tasty
    - tasty-hunit
